### ISSUE TITLE
Unhandled TypeError

### ISSUE THREAD

**Issue by igorank** [flowkeeper-org/fk-desktop#36] opened 2024-11-10 20:05 UTC
After I click start Pomodoro I immediately get this error:
![image](https://github.com/user-attachments/assets/560f6ee0-8b91-4afc-90fb-90badca2f82e)

```
Traceback (most recent call last):
  File "fk\qt\qt_timer.py", line 57, in <lambda>
  File "fk\qt\qt_timer.py", line 64, in _call
TypeError: Tutorial._on_pomodoro_work_start.<locals>.do() takes 1 positional argument but 2 were given
```

**Comment by co-stig** [comment] 2024-11-25 11:32
Thanks for the report! It's a duplicate of https://github.com/flowkeeper-org/fk-desktop/issues/37, fixed in the latest update.

**Closed by co-stig** 2024-11-25 11:32 UTC
